name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model."
    required: false
    default: "gpt-4"
  OPENAI_API_ENDPOINT:
    description: "OpenAI API endpoint."
    required: false
    default: ""
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: vx.x

    - name: Run AI review script
      shell: bash
      env:
        GITHUB_EVENT_PATH:    ${{ github.event_path }}
        GITHUB_TOKEN:         ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY:       ${{ inputs.OPENAI_API_KEY }}
        OPENAI_API_MODEL:     ${{ inputs.OPENAI_API_MODEL }}
        OPENAI_API_ENDPOINT:  ${{ inputs.OPENAI_API_ENDPOINT }}
        exclude:              ${{ inputs.exclude }}
      run: deno run "$GITHUB_ACTION_PATH/main.ts" --allow-read --allow-env --allow-net
branding:
  icon: "aperture"
  color: "green"
