name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model."
    required: false
    default: "gpt-4"
  OPENAI_API_ENDPOINT:
    description: "OpenAI API endpoint."
    required: false
    default: ""
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Set RUNNER_PATH based on OS
      run: |
        echo "Detected runner OS: $RUNNER_OS"
        if [ "$RUNNER_OS" = "Linux" ]; then
          echo "RUNNER_PATH=dist/action-linux" >> $GITHUB_ENV
        elif [ "$RUNNER_OS" = "macOS" ]; then
          echo "RUNNER_PATH=dist/action-osx" >> $GITHUB_ENV
        elif [ "$RUNNER_OS" = "Windows" ]; then
          echo "RUNNER_PATH=dist/action-windows.exe" >> $GITHUB_ENV
        fi
      shell: bash
    - name: Run native AI Code Review binary
      shell: bash
      env:
        GITHUB_EVENT_PATH:    ${{ github.event_path }}
        GITHUB_TOKEN:         ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY:       ${{ inputs.OPENAI_API_KEY }}
        OPENAI_API_MODEL:     ${{ inputs.OPENAI_API_MODEL }}
        OPENAI_API_ENDPOINT:  ${{ inputs.OPENAI_API_ENDPOINT }}
        exclude:              ${{ inputs.exclude }}
      run: |
        chmod +x "$GITHUB_ACTION_PATH/$RUNNER_PATH"
        $GITHUB_ACTION_PATH/$RUNNER_PATH
branding:
  icon: "aperture"
  color: "green"
